# PPO Trainer Configuration for Pendulum-v1
# This configuration uses the new configurable trainer system

defaults:
  - env: gym
  - model: tanh_normal
  - model@models.policy_model: tanh_normal
  - model@models.value_model: value
  - network: mlp
  - network@networks.policy_network: mlp
  - network@networks.value_network: mlp
  - collector: sync
  - replay_buffer: base
  - storage: tensor
  - sampler: random
  - writer: round_robin
  - trainer: ppo
  - optimizer: adam
  - loss: ppo
  - logger: null
  - _self_

# Network configurations
networks:
  policy_network:
    out_features: 2  # Pendulum action space is 1-dimensional
    in_features: 3   # Pendulum observation space is 3-dimensional

  value_network:
    out_features: 1  # Value output
    in_features: 3   # Pendulum observation space

# Model configurations
models:
  policy_model:
    return_log_prob: true
    in_keys: ["observation"]
    param_keys: ["loc", "scale"]
    out_keys: ["action"]
    network: ${networks.policy_network}

  value_model:
    in_keys: ["observation"]
    out_keys: ["state_value"]
    network: ${networks.value_network}

# Environment configuration
env:
  env_name: Pendulum-v1

# Storage configuration
storage:
  max_size: 1000
  device: cpu
  ndim: 1

# Replay buffer configuration
replay_buffer:
  storage: ${storage}
  sampler: ${sampler}
  writer: ${writer}

# Loss configuration
loss:
  actor_network: ${models.policy_model}
  critic_network: ${models.value_model}

# Optimizer configuration
optimizer:
  lr: 0.001

# Collector configuration
collector:
  create_env_fn: ${env}
  policy: ${models.policy_model}
  total_frames: 100_000
  frames_per_batch: 1024

# Trainer configuration
trainer:
  collector: ${collector}
  optimizer: ${optimizer}
  replay_buffer: ${replay_buffer}
  loss_module: ${loss}
  logger: ${logger}
  total_frames: 1000
  frame_skip: 1
  clip_grad_norm: true
  clip_norm: 100.0
  progress_bar: true
  seed: 42
  save_trainer_interval: 100
  log_interval: 100
  save_trainer_file: null
  optim_steps_per_batch: 1 
